blank_issues_enabled: false
contact_links:
  - name: WhatsApp community
    url: https://chat.whatsapp.com/KkVOY76T0go1J6lGElwQJg?mode=gi_t
    about: Talk with other Button Box builders on WhatsApp.
