#!/bin/sh
set -eu

case "${1:-}" in
  HOTSPOT|CONNECTING)
    exec /usr/bin/systemctl --no-block start comitup-web.service
    ;;
  CONNECTED)
    PYTHONPATH=/opt/messagebox /usr/bin/python3 -m messagebox.wifi_watchdog --configure
    exit 0
    ;;
  *)
    exit 64
    ;;
esac
